version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: mongodb-credit
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: credit-behavior-api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
    volumes:
      - ./models:/app/models
      - ./data:/app/data

volumes:
  mongo_data:
  